service: forex

frameworkVersion: "<=1.6.1"

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-west-2
  environment:
    CLIENT_ID: ''
    CLIENT_SECRET: 
    INSTALL_SUCCESS_URL: https://s3-us-west-2.amazonaws.com/forex-dev-serverlessdeploymentbucket-o150tudg9vb9/success.html
    INSTALL_ERROR_URL: https://s3-us-west-2.amazonaws.com/forex-dev-serverlessdeploymentbucket-o150tudg9vb9/error.html

functions:
  install:
    handler: install.handler
    events:
      - http:
          path: install
          method: get
