service: forex

frameworkVersion: "<=1.6.1"

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-west-2
  environment:
    CLIENT_ID: ''
    ClIENT_SECRET: 
    INSTALL_SUCCESS_URL: http://serverlessslackbot.s3-website-us-west-2.amazonaws.com/#success
    INSTALL_ERROR_URL: http://serverlessslackbot.s3-website-us-west-2.amazonaws.com/#error

functions:
  install:
    handler: install.handler
    events:
      - http:
           path: install
           method: get
