service: forex

frameworkVersion: "<=1.6.1"

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-west-2
  environment:
    CLIENT_ID: '239594296340.240813514535'
    ClIENT_SECRET: 0b93698513a87899a038c964f778a8fe
    INSTALL_SUCCESS_URL: http://serverlessslackbot.s3-website-us-west-2.amazonaws.com/#success
    INSTALL_ERROR_URL: http://serverlessslackbot.s3-website-us-west-2.amazonaws.com/#error

functions:
  install:
    handler: install.handler
    events:
      - http:
           path: install
           method: get

functions:
  hello:
    handler: handler.hello
